image: quay.io/python-devs/ci-image

before_script:
  - date && date -u
  - virtualenv ~/venv
  - source ~/venv/bin/activate
  - pip install -r requirements-dev.txt
  - apt-get install shellcheck
  - echo -n ${TNU_GOOGLE_APPLICATION_CREDENTIALS} | base64 -d > gcp-creds.json
  - export TNU_GOOGLE_APPLICATION_CREDENTIALS="gcp-creds.json"
  - export GOOGLE_APPLICATION_CREDENTIALS="gcp-creds.json"

stages:
  - test

test:
  script:
    - make -j4 test
